# for now, have to enable web plugin, see: https://github.com/linuxserver/docker-beets/issues/19
plugins: fetchart embedart scrub replaygain lastgenre chroma web
directory: /music
library: /config/musiclibrary.blb
art_filename: cover
threaded: yes
original_date: no
per_disc_numbering: no

paths:
    default: $albumartist/$album%aunique{}/$track $title
    singleton: Non-Album/$artist - $title
    comp: Compilations/$album%aunique{}/$track - $title
    albumtype_soundtrack: Soundtracks/$album/$track $title 

match:
    distance_weights:
        # do not care about missing tracks
        missing_tracks: 1
        
# we import automically and quietely to avoid asking for user feedback
# when an import has completed successfully, pymix will remove the src
# dir of the imported files.
import:
    write: yes
    copy: yes
    move: no
    resume: ask
    incremental: no
    incremental_skip_later: no
    quiet_fallback: asis
    timid: no
    log: /config/beet.log
    # the first import is made in quiet mode (set as a CLI param), whereas subsequent imports are not to allow user to manually set musicbrainz id.
    quiet: no

lastgenre:
    auto: yes
    source: album

embedart:
    auto: yes

fetchart:
    auto: yes
    
replaygain:
    auto: no

scrub:
    auto: yes

replace:
    '^\.': _
    '[\x00-\x1f]': _
    '[<>:"\?\*\|]': _
    '[\xE8-\xEB]': e
    '[\xEC-\xEF]': i
    '[\xE2-\xE6]': a
    '[\xF2-\xF6]': o
    '[\xF8]': o
    '\.$': _
    '\s+$': ''


web:
    host: 0.0.0.0
    readonly: no
