version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    user: "${UID}:${GID}"
    ports:
      - 443:8080
    volumes:
      - /Users/lukepurnell/workspace/filebrowser/data:/data
      - /Users/lukepurnell/workspace/filebrowser/config:/config
    environment:
      - FB_BASEURL=/filebrowser
    restart: always
