---
version: "2.1"
services:
  beets:
    image: lscr.io/linuxserver/beets:latest
    container_name: beets
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /Users/lajp/traefik/beets/config:/config
      - /Users/lajp/nav_music:/music
      - /Users/lajp/traefik/beets/download:/downloads
    ports:
      - 8337:8337
    restart: unless-stopped
